site_name: Bitprim
site_url: http://www.bitprim.org
site_description: Bitprim
site_author: Bitprim Team

repo_url: https://github.com/bitprim/bitprim-docs/
edit_uri: ""

docs_dir: content

theme:
    name: flatly

pages:
    - Home: index.md
    - User Guide:
        - Introduction: user_guide/introduction.md 
        - Installation: user_guide/installation.md
        - RPC: user_guide/rpc.md
        - Release Notes: user_guide/releases_notes.md 
    - Developer Guide:
        - Introduction: developer_guide/introduction.md
        - Rest Api: developer_guide/restapi/introduction.md
        - .Net: 
            - Introduction: developer_guide/dotnet/dotnet-Interface.md
            
        - C:
            - Introduction: developer_guide/c/C-interface.md
            
        - C++: 
            - Introduction: developer_guide/c++/C---interface.md
        - Python: 
            - Introduction: developer_guide/python/Python-interface.md
            
        - Go:
            - Introduction: developer_guide/go/Go-interface.md
    - About:
        - Team: team.md
        
copyright: Copyright &copy; 2018 Bitprim - info@bitprim.org

markdown_extensions:
    - toc:
        permalink: ☍
    - extra

plugins:
    - search    